apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: happy
  name: happy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: happy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: happy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
